# Generated by Django 6.0.1 on 2026-01-27 15:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0002_car_order_order_line'),
    ]

    operations = [
        migrations.AlterField(
            model_name='car',
            name='model',
            field=models.CharField(),
        ),
        migrations.AlterField(
            model_name='car',
            name='vin_code',
            field=models.CharField(max_length=17),
        ),
    ]
