# Generated by Django 6.0.1 on 2026-01-28 11:32

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0004_rename_car_id_order_car_alter_order_date_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='car',
            options={'verbose_name': 'Automobilis', 'verbose_name_plural': 'Automobiliai'},
        ),
        migrations.AlterModelOptions(
            name='order',
            options={'verbose_name': 'Užsakymas', 'verbose_name_plural': 'Užsakymai'},
        ),
        migrations.AlterModelOptions(
            name='service',
            options={'verbose_name': 'Servisas', 'verbose_name_plural': 'Servisai'},
        ),
    ]
