# Generated by Django 6.0.1 on 2026-01-29 11:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('autoservice', '0005_alter_car_options_alter_order_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='orderline',
            options={'verbose_name': 'Užsakymo eilutė', 'verbose_name_plural': 'Užsakymo eilutė'},
        ),
        migrations.AddField(
            model_name='order',
            name='status',
            field=models.CharField(choices=[('p', 'Priimtas'), ('v', 'Vykdomas'), ('t', 'Testuojama'), ('u', 'Užbaigtas'), ('a', 'Atšauktas')], default='p', max_length=1),
        ),
        migrations.AlterField(
            model_name='orderline',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='autoservice.order'),
        ),
    ]
